/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation {
	double first;
	double second;
};
typedef struct operation operation;

struct response {
	int error;
	union {
		double result;
	} response_u;
};
typedef struct response response;

#define CALCULADORAPROG 0x20000001
#define CALCULADORAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  response * suma_1(operation , CLIENT *);
extern  response * suma_1_svc(operation , struct svc_req *);
#define RESTA 2
extern  response * resta_1(operation , CLIENT *);
extern  response * resta_1_svc(operation , struct svc_req *);
#define MULTIPLICACION 3
extern  response * multiplicacion_1(operation , CLIENT *);
extern  response * multiplicacion_1_svc(operation , struct svc_req *);
#define DIVISION 4
extern  response * division_1(operation , CLIENT *);
extern  response * division_1_svc(operation , struct svc_req *);
extern int calculadoraprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  response * suma_1();
extern  response * suma_1_svc();
#define RESTA 2
extern  response * resta_1();
extern  response * resta_1_svc();
#define MULTIPLICACION 3
extern  response * multiplicacion_1();
extern  response * multiplicacion_1_svc();
#define DIVISION 4
extern  response * division_1();
extern  response * division_1_svc();
extern int calculadoraprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation (XDR *, operation*);
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_operation ();
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
