/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static responseBasic *
_suma_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(*argp, rqstp));
}

static responseBasic *
_resta_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(*argp, rqstp));
}

static responseBasic *
_multiplicacion_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(*argp, rqstp));
}

static responseBasic *
_division_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (division_1_svc(*argp, rqstp));
}

static responseBasic *
_logaritmo_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (logaritmo_1_svc(*argp, rqstp));
}

static responseBasic *
_potencia_1 (operationBasic  *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(*argp, rqstp));
}

static responseVectores *
_sumavectores_1 (operationVectores  *argp, struct svc_req *rqstp)
{
	return (sumavectores_1_svc(*argp, rqstp));
}

static responseVectores *
_restavectores_1 (operationVectores  *argp, struct svc_req *rqstp)
{
	return (restavectores_1_svc(*argp, rqstp));
}

static responseBasic *
_prodescalar3d_1 (operationVectores3D  *argp, struct svc_req *rqstp)
{
	return (prodescalar3d_1_svc(*argp, rqstp));
}

static responseVectores *
_prodvectorial3d_1 (operationVectores3D  *argp, struct svc_req *rqstp)
{
	return (prodvectorial3d_1_svc(*argp, rqstp));
}

static responseVectores *
_sumamatrices_1 (operationMatrices  *argp, struct svc_req *rqstp)
{
	return (sumamatrices_1_svc(*argp, rqstp));
}

static void
calculadoraprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operationBasic suma_1_arg;
		operationBasic resta_1_arg;
		operationBasic multiplicacion_1_arg;
		operationBasic division_1_arg;
		operationBasic logaritmo_1_arg;
		operationBasic potencia_1_arg;
		operationVectores sumavectores_1_arg;
		operationVectores restavectores_1_arg;
		operationVectores3D prodescalar3d_1_arg;
		operationVectores3D prodvectorial3d_1_arg;
		operationMatrices sumamatrices_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case LOGARITMO:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _logaritmo_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_operationBasic;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case SUMAVECTORES:
		_xdr_argument = (xdrproc_t) xdr_operationVectores;
		_xdr_result = (xdrproc_t) xdr_responseVectores;
		local = (char *(*)(char *, struct svc_req *)) _sumavectores_1;
		break;

	case RESTAVECTORES:
		_xdr_argument = (xdrproc_t) xdr_operationVectores;
		_xdr_result = (xdrproc_t) xdr_responseVectores;
		local = (char *(*)(char *, struct svc_req *)) _restavectores_1;
		break;

	case PRODESCALAR3D:
		_xdr_argument = (xdrproc_t) xdr_operationVectores3D;
		_xdr_result = (xdrproc_t) xdr_responseBasic;
		local = (char *(*)(char *, struct svc_req *)) _prodescalar3d_1;
		break;

	case PRODVECTORIAL3D:
		_xdr_argument = (xdrproc_t) xdr_operationVectores3D;
		_xdr_result = (xdrproc_t) xdr_responseVectores;
		local = (char *(*)(char *, struct svc_req *)) _prodvectorial3d_1;
		break;

	case SUMAMATRICES:
		_xdr_argument = (xdrproc_t) xdr_operationMatrices;
		_xdr_result = (xdrproc_t) xdr_responseVectores;
		local = (char *(*)(char *, struct svc_req *)) _sumamatrices_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORAPROG, CALCULADORAVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORAPROG, CALCULADORAVERS, calculadoraprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORAPROG, CALCULADORAVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORAPROG, CALCULADORAVERS, calculadoraprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORAPROG, CALCULADORAVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
